# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.0
_src_path: https://github.com/Kludex/python-template
description: An awesome package is coming soon! 🎉
email: marcelotryle@gmail.com
full_name: Marcelo Trylesinski
github: Kludex
project_name: WakaTime Client
twitter: marcelotryle
